## Preprocessing

In [1]:
# !pip install keras-tuner

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import pandas as pd
import tensorflow as tf
import sklearn as skl
import keras_tuner as kt
from pprint import pprint
from tensorflow.keras.models import load_model, save_model

2023-12-18 22:47:32.764430: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [3]:
#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dla-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
application_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   EIN                     34299 non-null  int64
 1   NAME                    34299 non-null  object
 2   APPLICATION_TYPE        34299 non-null  object
 3   AFFILIATION             34299 non-null  object
 4   CLASSIFICATION          34299 non-null  object
 5   USE_CASE                34299 non-null  object
 6   ORGANIZATION            34299 non-null  object
 7   STATUS                  34299 non-null  int64
 8   INCOME_AMT              34299 non-null  object
 9   SPECIAL_CONSIDERATIONS  34299 non-null  object
 10  ASK_AMT                 34299 non-null  int64
 11  IS_SUCCESSFUL           34299 non-null  int64
dtypes: int64(4), object(8)
memory usage: 3.1+ MB

In [5]:
# Copy the original df
application_copy_df =  application_df.copy()

In [6]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_copy_df = application_copy_df.drop(columns=['EIN', 'NAME'])
application_copy_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [7]:
# Determine the number of unique values in each column.
application_copy_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [8]:
# Look at APPLICATION_TYPE value counts for binning
application_copy_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [9]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cut_off = 200
application_types_to_replace = application_copy_df['APPLICATION_TYPE'].value_counts()\
                                [application_copy_df['APPLICATION_TYPE'].value_counts() < cut_off]\
                                .index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_copy_df['APPLICATION_TYPE'] = application_copy_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_copy_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [10]:
# Check the items in Other
application_copy_df['APPLICATION_TYPE'].value_counts()\
                                [application_copy_df['APPLICATION_TYPE'].value_counts() < cut_off]

Series([], Name: count, dtype: int64)

In [11]:
# (Alternative solution) Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cut_off = 200
application_types_to_replace = ['T9','T13','T12','T2','T25','T14','T29','T15','T17']

# Replace in dataframe
for app in application_types_to_replace:
    application_copy_df['APPLICATION_TYPE'] = application_copy_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_copy_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [12]:
# Look at CLASSIFICATION value counts for binning
application_copy_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C1248        1
C6100        1
C1820        1
C1900        1
C2150        1
Name: count, Length: 71, dtype: int64

In [13]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE

In [14]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
cut_off = 800
classifications_to_replace = application_copy_df['CLASSIFICATION'].value_counts()\
                                [application_copy_df['CLASSIFICATION'].value_counts() < cut_off]\
                                .index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_copy_df['CLASSIFICATION'] = application_copy_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_copy_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [15]:
# Return all the object columns
application_copy_df.dtypes[application_copy_df.dtypes == "object"]

APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
dtype: object

In [16]:
# Generate categorical variable list
application_cat = application_copy_df.dtypes[application_copy_df.dtypes == "object"].index.tolist()
application_cat

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [17]:
# Check unique values in the application_cat list
application_copy_df[application_cat].nunique()

APPLICATION_TYPE          9
AFFILIATION               6
CLASSIFICATION            6
USE_CASE                  5
ORGANIZATION              4
INCOME_AMT                9
SPECIAL_CONSIDERATIONS    2
dtype: int64

In [18]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(application_copy_df[application_cat]))

# Add the encoded variable names to the dataframe
encode_df.columns = enc.get_feature_names_out(application_cat)
encode_df.head()

/Users/rachelmmm/anaconda3/envs/PythonData/lib/python3.11/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8,AFFILIATION_CompanySponsored,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [19]:
application_copy_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [20]:
# Merge one-hot encoded features and drop the originals
application_encoded_df = application_copy_df.merge(encode_df,left_index=True, right_index=True)
application_encoded_df = application_encoded_df.drop(application_cat, axis=1)
application_encoded_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,1,5000,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,1,5000,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,1,5000,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,1,36500179,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [21]:
# Check all columns of the encoded dataframe
application_encoded_df.columns

Index(['STATUS', 'ASK_AMT', 'IS_SUCCESSFUL', 'APPLICATION_TYPE_Other',
       'APPLICATION_TYPE_T10', 'APPLICATION_TYPE_T19', 'APPLICATION_TYPE_T3',
       'APPLICATION_TYPE_T4', 'APPLICATION_TYPE_T5', 'APPLICATION_TYPE_T6',
       'APPLICATION_TYPE_T7', 'APPLICATION_TYPE_T8',
       'AFFILIATION_CompanySponsored', 'AFFILIATION_Family/Parent',
       'AFFILIATION_Independent', 'AFFILIATION_National', 'AFFILIATION_Other',
       'AFFILIATION_Regional', 'CLASSIFICATION_C1000', 'CLASSIFICATION_C1200',
       'CLASSIFICATION_C2000', 'CLASSIFICATION_C2100', 'CLASSIFICATION_C3000',
       'CLASSIFICATION_Other', 'USE_CASE_CommunityServ', 'USE_CASE_Heathcare',
       'USE_CASE_Other', 'USE_CASE_Preservation', 'USE_CASE_ProductDev',
       'ORGANIZATION_Association', 'ORGANIZATION_Co-operative',
       'ORGANIZATION_Corporation', 'ORGANIZATION_Trust', 'INCOME_AMT_0',
       'INCOME_AMT_1-9999', 'INCOME_AMT_10000-24999',
       'INCOME_AMT_100000-499999', 'INCOME_AMT_10M-50M', 'INCOME_AMT_1M-5M',
       'INCOME_AMT_25000-99999', 'INCOME_AMT_50M+', 'INCOME_AMT_5M-10M',
       'SPECIAL_CONSIDERATIONS_N', 'SPECIAL_CONSIDERATIONS_Y'],
      dtype='object')

In [22]:
# Split our preprocessed data into our features and target arrays
y = application_encoded_df['IS_SUCCESSFUL'].values
X = application_encoded_df.drop('IS_SUCCESSFUL', axis = 1).values

In [23]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [24]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model
## Test model 1 - reducing the number of neurons for each layer to 5

In [25]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0]) # number of columns
hidden_nodes_layer1 =  9

nn1 = tf.keras.models.Sequential()

# First hidden layer
nn1.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Output layer
nn1.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 9)                 396

 dense_1 (Dense)             (None, 1)                 10

=================================================================
Total params: 406 (1.59 KB)
Trainable params: 406 (1.59 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [26]:
# Compile the model
nn1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [27]:
# Train the model
fit_model = nn1.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 1ms/step - loss: 0.6033 - accuracy: 0.6952
Epoch 2/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5644 - accuracy: 0.7254
Epoch 3/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5603 - accuracy: 0.7268
Epoch 4/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5577 - accuracy: 0.7292
Epoch 5/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5563 - accuracy: 0.7283
Epoch 6/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5550 - accuracy: 0.7299
Epoch 7/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5542 - accuracy: 0.7319
Epoch 8/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5536 - accuracy: 0.7324
Epoch 9/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5527 - accuracy: 0.7324
Epoch 10/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5523 - accuracy: 0.7312
Epoch 11/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5516 - accuracy: 0.7324
Epoch 12/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5510 - accuracy: 0.7319
Epoch 13/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5508 - accuracy: 0.7318
Epoch 14/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5506 - accuracy: 0.7337
Epoch 15/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5501 - accuracy: 0.7320
Epoch 16/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5499 - accuracy: 0.7329
Epoch 17/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5496 - accuracy: 0.7327
Epoch 18/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5498 - accuracy: 0.7320
Epoch 19/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5493 - accuracy: 0.7331
Epoch 20/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5489 - accuracy: 0.7330
Epoch 21/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5490 - accuracy: 0.7332
Epoch 22/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5489 - accuracy: 0.7332
Epoch 23/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5488 - accuracy: 0.7333
Epoch 24/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5489 - accuracy: 0.7330
Epoch 25/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5487 - accuracy: 0.7335
Epoch 26/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5485 - accuracy: 0.7339
Epoch 27/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5484 - accuracy: 0.7346
Epoch 28/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5485 - accuracy: 0.7336
Epoch 29/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5481 - accuracy: 0.7332
Epoch 30/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5482 - accuracy: 0.7337
Epoch 31/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5480 - accuracy: 0.7334
Epoch 32/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5481 - accuracy: 0.7336
Epoch 33/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5480 - accuracy: 0.7343
Epoch 34/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5478 - accuracy: 0.7342
Epoch 35/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5477 - accuracy: 0.7336
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5478 - accuracy: 0.7344
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5477 - accuracy: 0.7320
Epoch 38/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5478 - accuracy: 0.7345
Epoch 39/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5476 - accuracy: 0.7341
Epoch 40/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5471 - accuracy: 0.7342
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5472 - accuracy: 0.7342
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7326
Epoch 43/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7339
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5471 - accuracy: 0.7337
Epoch 45/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5471 - accuracy: 0.7346
Epoch 46/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7345
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5470 - accuracy: 0.7345
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5468 - accuracy: 0.7350
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7340
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7344
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7348
Epoch 52/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7344
Epoch 53/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7351
Epoch 54/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7349
Epoch 55/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7350
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5466 - accuracy: 0.7348
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7351
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5465 - accuracy: 0.7341
Epoch 59/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7344
Epoch 60/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7345
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7345
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7341
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5462 - accuracy: 0.7345
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5465 - accuracy: 0.7344
Epoch 65/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7352
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5464 - accuracy: 0.7346
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7347
Epoch 68/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5462 - accuracy: 0.7338
Epoch 69/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5462 - accuracy: 0.7347
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5463 - accuracy: 0.7337
Epoch 71/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5460 - accuracy: 0.7350
Epoch 72/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7352
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5462 - accuracy: 0.7352
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5462 - accuracy: 0.7344
Epoch 75/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7341
Epoch 76/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5461 - accuracy: 0.7346
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7350
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5463 - accuracy: 0.7346
Epoch 79/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7351
Epoch 80/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7344
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7341
Epoch 82/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7343
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5458 - accuracy: 0.7349
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7349
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5461 - accuracy: 0.7345
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7353
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7349
Epoch 88/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5460 - accuracy: 0.7335
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5460 - accuracy: 0.7343
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7350
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7348
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7337
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5460 - accuracy: 0.7338
Epoch 94/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5461 - accuracy: 0.7336
Epoch 95/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5456 - accuracy: 0.7338
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7348
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7341
Epoch 98/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7342
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7352
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5458 - accuracy: 0.7345

In [28]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn1.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5538 - accuracy: 0.7251 - 562ms/epoch - 2ms/step
Loss: 0.5538011193275452, Accuracy: 0.7251312136650085

## Test model 2 - adding an extra layer

In [29]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0]) # number of columns
hidden_nodes_layer1 =  5
hidden_nodes_layer2 = 5

nn2 = tf.keras.models.Sequential()

# First hidden layer
nn2.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn2.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Third hidden layer
nn2.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))


# Output layer
nn2.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn2.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_2 (Dense)             (None, 5)                 220

 dense_3 (Dense)             (None, 5)                 30

 dense_4 (Dense)             (None, 5)                 30

 dense_5 (Dense)             (None, 1)                 6

=================================================================
Total params: 286 (1.12 KB)
Trainable params: 286 (1.12 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [30]:
# Compile the model
nn2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [31]:
# Train the model
fit_model = nn2.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.6416 - accuracy: 0.6491
Epoch 2/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5854 - accuracy: 0.7130
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5721 - accuracy: 0.7170
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5684 - accuracy: 0.7192
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5663 - accuracy: 0.7212
Epoch 6/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5645 - accuracy: 0.7224
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5627 - accuracy: 0.7227
Epoch 8/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5607 - accuracy: 0.7251
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5594 - accuracy: 0.7255
Epoch 10/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5578 - accuracy: 0.7258
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5565 - accuracy: 0.7264
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5557 - accuracy: 0.7283
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5544 - accuracy: 0.7290
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5538 - accuracy: 0.7306
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5532 - accuracy: 0.7317
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5527 - accuracy: 0.7317
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5524 - accuracy: 0.7310
Epoch 18/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5520 - accuracy: 0.7307
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5519 - accuracy: 0.7315
Epoch 20/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5518 - accuracy: 0.7311
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5517 - accuracy: 0.7312
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5515 - accuracy: 0.7317
Epoch 23/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5511 - accuracy: 0.7325
Epoch 24/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5515 - accuracy: 0.7304
Epoch 25/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5512 - accuracy: 0.7318
Epoch 26/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5509 - accuracy: 0.7324
Epoch 27/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5509 - accuracy: 0.7315
Epoch 28/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5510 - accuracy: 0.7316
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5506 - accuracy: 0.7316
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5509 - accuracy: 0.7328
Epoch 31/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5504 - accuracy: 0.7325
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5501 - accuracy: 0.7331
Epoch 33/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5502 - accuracy: 0.7325
Epoch 34/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5502 - accuracy: 0.7325
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5502 - accuracy: 0.7326
Epoch 36/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5502 - accuracy: 0.7323
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5501 - accuracy: 0.7327
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5502 - accuracy: 0.7317
Epoch 39/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5501 - accuracy: 0.7327
Epoch 40/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5499 - accuracy: 0.7327
Epoch 41/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5500 - accuracy: 0.7318
Epoch 42/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5499 - accuracy: 0.7324
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5498 - accuracy: 0.7325
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5499 - accuracy: 0.7323
Epoch 45/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5498 - accuracy: 0.7316
Epoch 46/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5498 - accuracy: 0.7334
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5498 - accuracy: 0.7327
Epoch 48/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5500 - accuracy: 0.7320
Epoch 49/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5495 - accuracy: 0.7327
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5498 - accuracy: 0.7320
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5497 - accuracy: 0.7319
Epoch 52/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5495 - accuracy: 0.7329
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5495 - accuracy: 0.7323
Epoch 54/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5496 - accuracy: 0.7321
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5493 - accuracy: 0.7325
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5496 - accuracy: 0.7328
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5491 - accuracy: 0.7319
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7325
Epoch 59/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5496 - accuracy: 0.7321
Epoch 60/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5493 - accuracy: 0.7328
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5495 - accuracy: 0.7331
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5492 - accuracy: 0.7325
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5493 - accuracy: 0.7319
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7326
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5493 - accuracy: 0.7323
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5489 - accuracy: 0.7327
Epoch 67/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5491 - accuracy: 0.7317
Epoch 68/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5493 - accuracy: 0.7322
Epoch 69/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5491 - accuracy: 0.7320
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5493 - accuracy: 0.7324
Epoch 71/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5490 - accuracy: 0.7326
Epoch 72/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5487 - accuracy: 0.7326
Epoch 73/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5490 - accuracy: 0.7324
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7338
Epoch 75/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5488 - accuracy: 0.7315
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5490 - accuracy: 0.7324
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5488 - accuracy: 0.7325
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7327
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5488 - accuracy: 0.7324
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5488 - accuracy: 0.7314
Epoch 81/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5488 - accuracy: 0.7324
Epoch 82/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5486 - accuracy: 0.7322
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5489 - accuracy: 0.7321
Epoch 84/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5488 - accuracy: 0.7320
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5484 - accuracy: 0.7319
Epoch 86/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5488 - accuracy: 0.7316
Epoch 87/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5488 - accuracy: 0.7318
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5491 - accuracy: 0.7336
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5491 - accuracy: 0.7329
Epoch 90/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5489 - accuracy: 0.7320
Epoch 91/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5486 - accuracy: 0.7324
Epoch 92/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5486 - accuracy: 0.7325
Epoch 93/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5488 - accuracy: 0.7325
Epoch 94/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5485 - accuracy: 0.7318
Epoch 95/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5487 - accuracy: 0.7329
Epoch 96/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5487 - accuracy: 0.7329
Epoch 97/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5484 - accuracy: 0.7333
Epoch 98/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5487 - accuracy: 0.7330
Epoch 99/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5490 - accuracy: 0.7323
Epoch 100/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5485 - accuracy: 0.7323

In [32]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn2.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5550 - accuracy: 0.7242 - 699ms/epoch - 3ms/step
Loss: 0.5550056099891663, Accuracy: 0.7241982221603394

## Model optimisation

In [33]:
# Create a method that creates a new Sequential model with hyperparameter options
def create_model(hp): #hyperparameter search object, hp refers to Hyperband in the cell below
    # when you call the create_model function within kt.Hyperband(), it will automatically pass in Hyperband in the function

    nn_model = tf.keras.models.Sequential()# finding the optimal hyperparameters for a Sequential model

    # Allow kerastuner to decide which activation function to use in hidden layers
    activation = hp.Choice('activation',['relu','tanh','sigmoid']) #allow Hyperband to select between different activation
    #functions during tuning process

    # Allow kerastuner to decide number of neurons in first layer
    #'first_units' is the name of the hyperparameter
    #name is used internally by the tuner to keep track of which hyperparameter it is adjusting and to log or
    #report the values it is testing
    nn_model.add(tf.keras.layers.Dense(units=hp.Int('first_units',
        min_value=1,
        max_value=10,
        step=2), activation=activation, input_dim=len(X_train[0]))) #increment in steps of 2

    # Allow kerastuner to decide number of hidden layers and neurons in hidden layers
    for i in range(hp.Int('num_layers', 1, 6)):
      units_name = 'units_' + str(i)
      print(f"Adding layer with {units_name}") # for debugging purposes
      nn_model.add(tf.keras.layers.Dense(units=hp.Int(units_name,
          min_value=1,
          max_value=10,
          step=2),
          activation=activation))



    # Define the output layer
    nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

    # Compile the model
    # can also use the tuner for loss function and optimiser as well
    nn_model.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])

    return nn_model

In [34]:
tuner = kt.Hyperband( #initialise a hyperband tuner
    create_model, #use the create_model function, this tells the Hyperband what is the architecture of your model
    objective="val_accuracy", # when searching for the optimal hyperparameter, assess it against the validation accuracy
    # what's the accuracy of the current model with the hyperparameters with the test set?
    max_epochs=20, #20 epochs for the hyperparameter tuning process => for each combination (e.g., relu with 10 neurons, run
    # 20 times)
    hyperband_iterations=2)

Adding layer with units_0

In [35]:
# Run the kerastuner search for best hyperparameters
tuner.search(X_train_scaled,y_train,epochs=20,validation_data=(X_test_scaled,y_test))

Trial 60 Complete [00h 00m 36s]
val_accuracy: 0.7254810333251953

Best val_accuracy So Far: 0.7285131216049194
Total elapsed time: 00h 20m 01s

## Return the best hyperparameter model

In [36]:
best_hyper = tuner.get_best_hyperparameters(1)[0] #returns the best hyperparameter model and access it using index
best_hyper.values

{'activation': 'relu',
 'first_units': 9,
 'num_layers': 2,
 'units_0': 5,
 'units_1': 7,
 'units_2': 9,
 'units_3': 9,
 'units_4': 9,
 'tuner/epochs': 20,
 'tuner/initial_epoch': 7,
 'tuner/bracket': 1,
 'tuner/round': 1,
 'tuner/trial_id': '0019',
 'units_5': 7}

## Test model 3

In [40]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0]) # number of columns
hidden_nodes_layer1 = 5
hidden_nodes_layer2 = 7

nn3 = tf.keras.models.Sequential()

# First hidden layer
nn3.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn3.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Output layer
nn3.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn3.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 5)                 220

 dense_7 (Dense)             (None, 5)                 30

 dense_8 (Dense)             (None, 1)                 6

=================================================================
Total params: 256 (1.00 KB)
Trainable params: 256 (1.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [41]:
# Compile the model
nn3.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [42]:
# Train the model
fit_model = nn3.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6330 - accuracy: 0.6903
Epoch 2/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5763 - accuracy: 0.7267
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5657 - accuracy: 0.7269
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5613 - accuracy: 0.7286
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5591 - accuracy: 0.7302
Epoch 6/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7305
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5575 - accuracy: 0.7308
Epoch 8/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5570 - accuracy: 0.7306
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5566 - accuracy: 0.7304
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5561 - accuracy: 0.7304
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5557 - accuracy: 0.7301
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5553 - accuracy: 0.7303
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5549 - accuracy: 0.7301
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5547 - accuracy: 0.7311
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5543 - accuracy: 0.7308
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5539 - accuracy: 0.7306
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5536 - accuracy: 0.7309
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5534 - accuracy: 0.7313
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5531 - accuracy: 0.7317
Epoch 20/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5529 - accuracy: 0.7316
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5529 - accuracy: 0.7332
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5528 - accuracy: 0.7328
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5525 - accuracy: 0.7311
Epoch 24/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5524 - accuracy: 0.7321
Epoch 25/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5518 - accuracy: 0.7328
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5522 - accuracy: 0.7319
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5519 - accuracy: 0.7322
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5516 - accuracy: 0.7315
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5520 - accuracy: 0.7329
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5515 - accuracy: 0.7324
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5512 - accuracy: 0.7320
Epoch 32/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5514 - accuracy: 0.7329
Epoch 33/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5511 - accuracy: 0.7333
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5511 - accuracy: 0.7330
Epoch 35/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5511 - accuracy: 0.7332
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5511 - accuracy: 0.7325
Epoch 37/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5512 - accuracy: 0.7326
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5510 - accuracy: 0.7328
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5509 - accuracy: 0.7323
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5510 - accuracy: 0.7331
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5508 - accuracy: 0.7326
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5508 - accuracy: 0.7332
Epoch 43/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5507 - accuracy: 0.7334
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5508 - accuracy: 0.7327
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5507 - accuracy: 0.7327
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5506 - accuracy: 0.7335
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5503 - accuracy: 0.7338
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5504 - accuracy: 0.7336
Epoch 49/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5505 - accuracy: 0.7337
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5503 - accuracy: 0.7332
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5504 - accuracy: 0.7339
Epoch 52/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5503 - accuracy: 0.7332
Epoch 53/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5502 - accuracy: 0.7337
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5504 - accuracy: 0.7332
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5498 - accuracy: 0.7340
Epoch 56/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5501 - accuracy: 0.7329
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5502 - accuracy: 0.7334
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5501 - accuracy: 0.7333
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5501 - accuracy: 0.7335
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5499 - accuracy: 0.7340
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5499 - accuracy: 0.7342
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5499 - accuracy: 0.7338
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5499 - accuracy: 0.7346
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5499 - accuracy: 0.7341
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5497 - accuracy: 0.7348
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5499 - accuracy: 0.7341
Epoch 67/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5498 - accuracy: 0.7339
Epoch 68/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5498 - accuracy: 0.7343
Epoch 69/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5496 - accuracy: 0.7343
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5498 - accuracy: 0.7345
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5500 - accuracy: 0.7344
Epoch 72/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5498 - accuracy: 0.7353
Epoch 73/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5496 - accuracy: 0.7341
Epoch 74/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5497 - accuracy: 0.7338
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5499 - accuracy: 0.7336
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5498 - accuracy: 0.7336
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5498 - accuracy: 0.7350
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5498 - accuracy: 0.7341
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5495 - accuracy: 0.7341
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5498 - accuracy: 0.7345
Epoch 81/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5496 - accuracy: 0.7338
Epoch 82/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5498 - accuracy: 0.7345
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5497 - accuracy: 0.7344
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5497 - accuracy: 0.7343
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5496 - accuracy: 0.7344
Epoch 86/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5497 - accuracy: 0.7338
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5497 - accuracy: 0.7338
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7341
Epoch 89/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5495 - accuracy: 0.7345
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7338
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5496 - accuracy: 0.7338
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7343
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5496 - accuracy: 0.7345
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5496 - accuracy: 0.7336
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5495 - accuracy: 0.7350
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7334
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5493 - accuracy: 0.7339
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5495 - accuracy: 0.7344
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5497 - accuracy: 0.7342
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7341

In [43]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn3.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5564 - accuracy: 0.7240 - 376ms/epoch - 1ms/step
Loss: 0.5564360618591309, Accuracy: 0.7239649891853333

In [44]:
# Export the model to HDF5 file
nn1.save("AlphabetSoupCharity_Optimisation.h5")

/Users/rachelmmm/anaconda3/envs/PythonData/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(